import json

from vuls.generation.crm_mvp import ensure_crm_next_mvp_manifest
from vuls.llm.schemas import GeneratedProjectFile, GeneratedProjectManifest, ProjectBrief


def car_wash_brief() -> ProjectBrief:
    return ProjectBrief(
        title="Car Wash CRM",
        goal="Create a CRM for a car wash",
        target_users=["owner", "staff"],
        must_have_features=["dashboard", "customers", "orders", "tasks"],
        language_code="en",
    )


def dentistry_brief() -> ProjectBrief:
    return ProjectBrief(
        title="Dentistry CRM",
        goal="Create a CRM for a dentistry clinic",
        target_users=["clinic manager", "front desk"],
        must_have_features=["dashboard", "customers", "orders", "tasks"],
        language_code="en",
    )


def fitness_brief() -> ProjectBrief:
    return ProjectBrief(
        title="Fitness Club CRM",
        goal="Create a CRM for a fitness club with members and trainers",
        target_users=["club manager", "trainer"],
        must_have_features=["members", "classes", "memberships"],
        language_code="en",
    )


def beauty_salon_brief() -> ProjectBrief:
    return ProjectBrief(
        title="Beauty Salon CRM",
        goal="Create a CRM for a beauty salon",
        target_users=["salon manager", "master"],
        must_have_features=["clients", "masters", "services", "bookings"],
        language_code="en",
    )


def auto_service_brief() -> ProjectBrief:
    return ProjectBrief(
        title="Auto Service CRM",
        goal="Create a CRM for an auto service repair shop",
        target_users=["service manager", "mechanic"],
        must_have_features=["vehicles", "mechanics", "repairs", "work orders"],
        language_code="en",
    )


def stub_manifest() -> GeneratedProjectManifest:
    return GeneratedProjectManifest(
        project_name="car-wash-crm",
        readme_summary="CRM for a car wash.",
        tech_stack=["Next.js"],
        files=[
            GeneratedProjectFile(
                path="README.md",
                content="# Car Wash CRM\n",
                purpose="Project documentation",
            ),
            GeneratedProjectFile(
                path="src/app/customers/page.tsx",
                content="export default function Page() { return <div>Customers</div>; }\n",
                purpose="Customer page placeholder",
            ),
        ],
    )


def dentistry_stub_manifest() -> GeneratedProjectManifest:
    return GeneratedProjectManifest(
        project_name="dentistry-crm",
        readme_summary="CRM for a dentistry clinic.",
        tech_stack=["Next.js"],
        files=[
            GeneratedProjectFile(
                path="README.md",
                content="# Dentistry CRM\n",
                purpose="Project documentation",
            ),
        ],
    )


def app_router_incompatible_manifest() -> GeneratedProjectManifest:
    return GeneratedProjectManifest(
        project_name="car-wash-crm",
        readme_summary="CRM for a car wash.",
        tech_stack=["Next.js"],
        files=[
            GeneratedProjectFile(
                path="README.md",
                content="# Car Wash CRM\n",
                purpose="Project documentation",
            ),
            GeneratedProjectFile(
                path="src/app/page.tsx",
                content=(
                    "import { useRouter } from 'next/router';\n"
                    "import { useEffect } from 'react';\n\n"
                    "export default function Page() {\n"
                    "  const router = useRouter();\n"
                    "  useEffect(() => {\n"
                    "    router.push('/dashboard');\n"
                    "  }, [router]);\n"
                    "  return <main>Redirecting to dashboard</main>;\n"
                    "}\n"
                ),
                purpose="Root route generated by the model.",
            ),
            GeneratedProjectFile(
                path="src/app/reports/page.tsx",
                content=(
                    "import { useRouter } from 'next/router';\n"
                    "import { useEffect } from 'react';\n\n"
                    "export default function ReportsPage() {\n"
                    "  const router = useRouter();\n"
                    "  useEffect(() => {\n"
                    "    router.prefetch('/dashboard');\n"
                    "  }, [router]);\n"
                    "  return <main>Reports</main>;\n"
                    "}\n"
                ),
                purpose="Extra App Router page generated by the model.",
            ),
        ],
    )


def incomplete_next_package_manifest() -> GeneratedProjectManifest:
    return GeneratedProjectManifest(
        project_name="fitness-crm",
        readme_summary="CRM for a fitness club.",
        tech_stack=["Next.js"],
        files=[
            GeneratedProjectFile(
                path="package.json",
                content=json.dumps(
                    {
                        "name": "fitness-crm",
                        "version": "1.0.0",
                        "scripts": {
                            "dev": "next dev",
                            "build": "next build",
                            "start": "next start",
                            "test": "jest",
                        },
                        "dependencies": {
                            "next": "latest",
                            "react": "^18.0.0",
                            "react-dom": "^18.0.0",
                            "@supabase/supabase-js": "^1.35.0",
                            "tailwindcss": "^3.0.0",
                        },
                        "devDependencies": {
                            "typescript": "^4.5.4",
                            "jest": "^27.4.5",
                        },
                    },
                    indent=2,
                ),
                purpose="Model-generated package manifest.",
            ),
        ],
    )


def incomplete_tsconfig_manifest() -> GeneratedProjectManifest:
    return GeneratedProjectManifest(
        project_name="car-service-crm",
        readme_summary="CRM for a car service.",
        tech_stack=["Next.js"],
        files=[
            GeneratedProjectFile(
                path="tsconfig.json",
                content=json.dumps(
                    {
                        "compilerOptions": {
                            "target": "es5",
                            "lib": ["dom", "dom.iterable", "esnext"],
                            "allowJs": True,
                            "skipLibCheck": True,
                            "strict": False,
                            "forceConsistentCasingInFileNames": True,
                            "noEmit": True,
                            "esModuleInterop": True,
                            "module": "esnext",
                            "moduleResolution": "node",
                            "resolveJsonModule": True,
                            "isolatedModules": True,
                            "jsx": "preserve",
                            "incremental": True,
                        },
                        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
                        "exclude": ["node_modules"],
                    },
                    indent=2,
                ),
                purpose="Model-generated TypeScript config.",
            ),
        ],
    )


def test_crm_mvp_enhancer_adds_required_next_app_router_files() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=stub_manifest(),
        template_key="crm",
        brief=car_wash_brief(),
    )

    paths = {file.path for file in manifest.files}

    assert {
        "package.json",
        "tsconfig.json",
        "tailwind.config.ts",
        "postcss.config.js",
        "schema.sql",
        "env.example",
        "src/app/layout.tsx",
        "src/app/globals.css",
        "src/app/page.tsx",
        "src/app/dashboard/page.tsx",
        "src/app/customers/actions.ts",
        "src/app/customers/page.tsx",
        "src/app/orders/actions.ts",
        "src/app/orders/page.tsx",
        "src/app/tasks/actions.ts",
        "src/app/tasks/page.tsx",
        "src/lib/database.types.ts",
        "src/lib/supabase.ts",
    }.issubset(paths)
    assert {"Next.js", "TypeScript", "Tailwind CSS"}.issubset(set(manifest.tech_stack))


def test_crm_mvp_enhancer_replaces_incomplete_package_manifest() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=incomplete_next_package_manifest(),
        template_key="crm",
        brief=car_wash_brief(),
    )
    files = {file.path: file.content for file in manifest.files}
    package_json = json.loads(files["package.json"])

    assert package_json["dependencies"]["next"].startswith("^15.")
    assert package_json["dependencies"]["@supabase/supabase-js"].startswith("^2.")
    assert "react-dom" in package_json["dependencies"]
    assert "autoprefixer" in package_json["devDependencies"]
    assert "postcss" in package_json["devDependencies"]
    assert "tailwindcss" in package_json["devDependencies"]
    assert "typescript" in package_json["devDependencies"]
    assert "@types/node" in package_json["devDependencies"]
    assert "@types/react" in package_json["devDependencies"]
    assert "@types/react-dom" in package_json["devDependencies"]
    assert package_json["scripts"]["build"] == "next build"
    assert "jest" not in package_json["devDependencies"]


def test_crm_mvp_enhancer_replaces_tsconfig_without_import_alias() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=incomplete_tsconfig_manifest(),
        template_key="crm",
        brief=car_wash_brief(),
    )
    files = {file.path: file.content for file in manifest.files}
    tsconfig = json.loads(files["tsconfig.json"])

    assert tsconfig["compilerOptions"]["moduleResolution"] == "bundler"
    assert tsconfig["compilerOptions"]["paths"] == {"@/*": ["./src/*"]}
    assert ".next/types/**/*.ts" in tsconfig["include"]


def test_crm_mvp_enhancer_replaces_placeholder_pages_with_real_react_code() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=stub_manifest(),
        template_key="crm",
        brief=car_wash_brief(),
    )
    files = {file.path: file.content for file in manifest.files}

    assert "<form" in files["src/app/customers/page.tsx"]
    assert "listCustomers" in files["src/app/customers/page.tsx"]
    assert "createCustomer" in files["src/app/customers/page.tsx"]
    assert "updateCustomer" in files["src/app/customers/page.tsx"]
    assert "deleteCustomer" in files["src/app/customers/page.tsx"]
    assert "Total Customers" in files["src/app/dashboard/page.tsx"]
    assert "Open Orders" in files["src/app/dashboard/page.tsx"]
    assert "listOrders" in files["src/app/orders/page.tsx"]
    assert "createOrder" in files["src/app/orders/page.tsx"]
    assert "updateOrderStatus" in files["src/app/orders/page.tsx"]
    assert "deleteOrder" in files["src/app/orders/page.tsx"]
    assert "order.status" in files["src/app/orders/page.tsx"]
    assert "listTasks" in files["src/app/tasks/page.tsx"]
    assert "task.status" in files["src/app/tasks/page.tsx"]


def test_crm_mvp_enhancer_generates_supabase_backed_mvp_without_mock_data() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=stub_manifest(),
        template_key="crm",
        brief=car_wash_brief(),
    )
    files = {file.path: file.content for file in manifest.files}
    all_content = "\n".join(files.values())

    assert "src/lib/mock-data.ts" not in files
    assert "mockCustomers" not in all_content
    assert "mockOrders" not in all_content
    assert "mockTasks" not in all_content
    assert "@supabase/supabase-js" in files["package.json"]
    assert "NEXT_PUBLIC_SUPABASE_URL" in files["env.example"]
    assert "NEXT_PUBLIC_SUPABASE_ANON_KEY" in files["env.example"]
    assert "createClient" in files["src/lib/supabase.ts"]
    assert "getSupabaseClient" in files["src/lib/supabase.ts"]
    assert "public.customers" in files["schema.sql"]
    assert "public.orders" in files["schema.sql"]
    assert "public.tasks" in files["schema.sql"]
    assert "enable row level security" in files["schema.sql"].casefold()


def test_crm_mvp_enhancer_generates_dentistry_crm_without_car_wash_copy() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=dentistry_stub_manifest(),
        template_key="crm",
        brief=dentistry_brief(),
    )
    files = {file.path: file.content for file in manifest.files}
    generated_content = "\n".join(files.values()).casefold()

    forbidden_domain_terms = [
        "car wash operations",
        "premium wash",
        "wash orders",
        "bay preparation",
        "car wash",
        "vehicle",
    ]

    for forbidden_term in forbidden_domain_terms:
        assert forbidden_term not in generated_content
    assert "dental clinic operations" in files["src/app/dashboard/page.tsx"].casefold()
    assert "patients" in files["src/app/customers/page.tsx"].casefold()
    assert "appointments" in files["src/app/orders/page.tsx"].casefold()
    assert "treatments" in files["src/app/tasks/page.tsx"].casefold()
    assert 'placeholder="Dental cleaning"' in files["src/app/orders/page.tsx"]


def test_crm_mvp_enhancer_generates_fitness_specific_terminology() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=dentistry_stub_manifest(),
        template_key="crm",
        brief=fitness_brief(),
    )
    files = {file.path: file.content for file in manifest.files}
    generated_content = "\n".join(files.values()).casefold()

    assert "fitness club operations" in generated_content
    assert "members" in generated_content
    assert "trainers" in generated_content
    assert "classes" in generated_content
    assert "memberships" in generated_content
    assert "strength class" in generated_content
    assert "premium wash" not in generated_content
    assert "car wash" not in generated_content


def test_crm_mvp_enhancer_supports_beauty_salon_domain_adapter() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=dentistry_stub_manifest(),
        template_key="crm",
        brief=beauty_salon_brief(),
    )
    generated_content = "\n".join(file.content for file in manifest.files).casefold()

    assert "beauty salon operations" in generated_content
    assert "clients" in generated_content
    assert "masters" in generated_content
    assert "services" in generated_content
    assert "bookings" in generated_content
    assert "hair styling" in generated_content


def test_crm_mvp_enhancer_supports_auto_service_domain_adapter() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=dentistry_stub_manifest(),
        template_key="crm",
        brief=auto_service_brief(),
    )
    generated_content = "\n".join(file.content for file in manifest.files).casefold()

    assert "auto service operations" in generated_content
    assert "vehicles" in generated_content
    assert "mechanics" in generated_content
    assert "repairs" in generated_content
    assert "work orders" in generated_content
    assert "brake repair" in generated_content


def test_crm_mvp_enhancer_removes_pages_router_imports_from_app_router_files() -> None:
    manifest = ensure_crm_next_mvp_manifest(
        manifest=app_router_incompatible_manifest(),
        template_key="crm",
        brief=car_wash_brief(),
    )
    app_files = {
        file.path: file.content
        for file in manifest.files
        if file.path.startswith("src/app/")
    }

    assert all("next/router" not in content for content in app_files.values())
    assert 'from "next/navigation"' in app_files["src/app/page.tsx"]
    assert "redirect" in app_files["src/app/page.tsx"]
    assert 'from "next/navigation"' in app_files["src/app/reports/page.tsx"]
    assert app_files["src/app/reports/page.tsx"].startswith('"use client";')


def test_crm_mvp_enhancer_does_not_change_non_crm_templates() -> None:
    manifest = stub_manifest()

    enhanced = ensure_crm_next_mvp_manifest(
        manifest=manifest,
        template_key="saas",
        brief=car_wash_brief(),
    )

    assert enhanced is manifest
